In [1]:
import tensorflow as tf
print(tf.__version__)


2.15.0


In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
### Vocabulary size
voc_size=500

# one hot repr

In [6]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[352, 364, 364, 201], [352, 364, 364, 263], [352, 385, 364, 72], [431, 263, 275, 259, 470], [431, 263, 275, 259, 492], [153, 352, 119, 364, 294], [28, 201, 232, 259]]


# word embedding rep

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 352 364 364 201]
 [  0   0   0   0 352 364 364 263]
 [  0   0   0   0 352 385 364  72]
 [  0   0   0 431 263 275 259 470]
 [  0   0   0 431 263 275 259 492]
 [  0   0   0 153 352 119 364 294]
 [  0   0   0   0  28 201 232 259]]


In [10]:
## 10 feature dimesnions
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5000 (19.53 KB)
Trainable params: 5000 (19.53 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 352, 364, 364, 201])

In [14]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 91ms/step


array([[ 0.03043275,  0.02272444,  0.00955646,  0.03351151,  0.01063633,
        -0.00974529, -0.01865082, -0.04437042,  0.0180861 ,  0.03811215],
       [ 0.03043275,  0.02272444,  0.00955646,  0.03351151,  0.01063633,
        -0.00974529, -0.01865082, -0.04437042,  0.0180861 ,  0.03811215],
       [ 0.03043275,  0.02272444,  0.00955646,  0.03351151,  0.01063633,
        -0.00974529, -0.01865082, -0.04437042,  0.0180861 ,  0.03811215],
       [ 0.03043275,  0.02272444,  0.00955646,  0.03351151,  0.01063633,
        -0.00974529, -0.01865082, -0.04437042,  0.0180861 ,  0.03811215],
       [-0.04158692,  0.00045289, -0.04723145,  0.04898385, -0.03420138,
        -0.03091275,  0.00793619, -0.013708  , -0.02886502,  0.00556868],
       [-0.00916495, -0.02499406, -0.02530382, -0.00513151,  0.04821327,
         0.04403341,  0.02501759,  0.03588105, -0.04248196,  0.04455204],
       [-0.00916495, -0.02499406, -0.02530382, -0.00513151,  0.04821327,
         0.04403341,  0.02501759,  0.03588105

In [15]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 47ms/step
[[[ 0.03043275  0.02272444  0.00955646  0.03351151  0.01063633
   -0.00974529 -0.01865082 -0.04437042  0.0180861   0.03811215]
  [ 0.03043275  0.02272444  0.00955646  0.03351151  0.01063633
   -0.00974529 -0.01865082 -0.04437042  0.0180861   0.03811215]
  [ 0.03043275  0.02272444  0.00955646  0.03351151  0.01063633
   -0.00974529 -0.01865082 -0.04437042  0.0180861   0.03811215]
  [ 0.03043275  0.02272444  0.00955646  0.03351151  0.01063633
   -0.00974529 -0.01865082 -0.04437042  0.0180861   0.03811215]
  [-0.04158692  0.00045289 -0.04723145  0.04898385 -0.03420138
   -0.03091275  0.00793619 -0.013708   -0.02886502  0.00556868]
  [-0.00916495 -0.02499406 -0.02530382 -0.00513151  0.04821327
    0.04403341  0.02501759  0.03588105 -0.04248196  0.04455204]
  [-0.00916495 -0.02499406 -0.02530382 -0.00513151  0.04821327
    0.04403341  0.02501759  0.03588105 -0.04248196  0.04455204]
  [-0.01524174  0.0296138  -0.0087603  -0.01427109  0.02767

In [16]:
embedded_docs[0]

array([  0,   0,   0,   0, 352, 364, 364, 201])

In [17]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 27ms/step
[[ 0.03043275  0.02272444  0.00955646  0.03351151  0.01063633 -0.00974529
  -0.01865082 -0.04437042  0.0180861   0.03811215]
 [ 0.03043275  0.02272444  0.00955646  0.03351151  0.01063633 -0.00974529
  -0.01865082 -0.04437042  0.0180861   0.03811215]
 [ 0.03043275  0.02272444  0.00955646  0.03351151  0.01063633 -0.00974529
  -0.01865082 -0.04437042  0.0180861   0.03811215]
 [ 0.03043275  0.02272444  0.00955646  0.03351151  0.01063633 -0.00974529
  -0.01865082 -0.04437042  0.0180861   0.03811215]
 [-0.04158692  0.00045289 -0.04723145  0.04898385 -0.03420138 -0.03091275
   0.00793619 -0.013708   -0.02886502  0.00556868]
 [-0.00916495 -0.02499406 -0.02530382 -0.00513151  0.04821327  0.04403341
   0.02501759  0.03588105 -0.04248196  0.04455204]
 [-0.00916495 -0.02499406 -0.02530382 -0.00513151  0.04821327  0.04403341
   0.02501759  0.03588105 -0.04248196  0.04455204]
 [-0.01524174  0.0296138  -0.0087603  -0.01427109  0.02767534  0.01369319

In [19]:
### Assignment

sent1=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [20]:
voc_size=1000

In [21]:
onehot_repr=[one_hot(words,voc_size)for words in sent1] 
print(onehot_repr)

[[351, 483, 887, 563, 536, 680], [935, 181, 887, 714, 406, 353], [695, 586, 400, 612], [351, 852, 887, 504, 351, 714], [68, 313, 892, 887, 714, 406, 353], [567, 887, 714, 406, 568, 708]]


In [22]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [23]:
import numpy as np

In [24]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[351 483 887 563 536 680   0   0]
 [935 181 887 714 406 353   0   0]
 [695 586 400 612   0   0   0   0]
 [351 852 887 504 351 714   0   0]
 [ 68 313 892 887 714 406 353   0]
 [567 887 714 406 568 708   0   0]]


In [25]:
## 10 feature dimesnions
dim=20

In [32]:
model=Sequential()
model.add(Embedding(voc_size,20,input_length=sent_length))
model.compile('adam','mse')

In [33]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 8, 20)             20000     
                                                                 
Total params: 20000 (78.12 KB)
Trainable params: 20000 (78.12 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [34]:
embedded_docs[0]

array([351, 483, 887, 563, 536, 680,   0,   0])

In [35]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 81ms/step


array([[-2.5146544e-02,  3.6129426e-02,  1.6120818e-02,  3.5024118e-02,
        -1.2963630e-02,  2.5676005e-03,  2.7465928e-02,  3.3033397e-02,
        -1.9860638e-02, -4.0886022e-02,  3.7952449e-02,  1.2585450e-02,
         9.1568604e-03,  3.6724512e-02,  4.1704301e-02, -4.4303026e-02,
        -4.1427493e-02, -2.9333962e-02,  3.2716382e-02,  2.7013216e-02],
       [ 2.8024424e-02, -4.9954094e-02,  2.7514983e-02,  4.6289790e-02,
        -1.4691900e-02,  2.5791083e-02, -1.1890136e-02, -4.4164181e-02,
         2.9482093e-02, -1.4872476e-04, -2.7786100e-02, -3.9528679e-02,
        -8.9319237e-03, -3.0391861e-02, -4.6414316e-02, -3.3300519e-02,
         4.6227861e-02, -2.7665902e-02,  2.5032390e-02,  1.6267609e-02],
       [ 3.9282430e-02,  3.6602728e-03,  4.7829952e-02,  1.9648883e-02,
        -2.7666653e-02,  2.8241072e-02,  4.6732638e-02,  1.4169071e-02,
        -3.6443673e-02, -4.8869956e-02,  3.8455155e-02, -4.9006868e-02,
         4.4258367e-02,  2.8193865e-02, -3.0132592e-02, -2.358

In [36]:
embedded_docs[0]

array([351, 483, 887, 563, 536, 680,   0,   0])

In [37]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 74ms/step
[[[-2.51465440e-02  3.61294262e-02  1.61208175e-02  3.50241177e-02
   -1.29636303e-02  2.56760046e-03  2.74659283e-02  3.30333970e-02
   -1.98606383e-02 -4.08860222e-02  3.79524492e-02  1.25854500e-02
    9.15686041e-03  3.67245115e-02  4.17043008e-02 -4.43030261e-02
   -4.14274931e-02 -2.93339621e-02  3.27163823e-02  2.70132162e-02]
  [ 2.80244239e-02 -4.99540940e-02  2.75149830e-02  4.62897904e-02
   -1.46919005e-02  2.57910825e-02 -1.18901357e-02 -4.41641808e-02
    2.94820927e-02 -1.48724765e-04 -2.77861003e-02 -3.95286791e-02
   -8.93192366e-03 -3.03918608e-02 -4.64143157e-02 -3.33005190e-02
    4.62278612e-02 -2.76659019e-02  2.50323899e-02  1.62676089e-02]
  [ 3.92824300e-02  3.66027281e-03  4.78299521e-02  1.96488835e-02
   -2.76666526e-02  2.82410719e-02  4.67326380e-02  1.41690709e-02
   -3.64436731e-02 -4.88699563e-02  3.84551547e-02 -4.90068682e-02
    4.42583673e-02  2.81938650e-02 -3.01325917e-02 -2.35895161e-02
   -3.00